source 'http://rubygems.org'

gem 'rails', '3.0.4'
gem 'sqlite3-ruby', '1.3.2', :require => 'sqlite3'
gem 'will_paginate', '3.0.pre2'
gem 'declarative_authorization'
gem 'ruby-openid'
gem 'rack-openid'
gem 'authlogic-oid'

group :development do
  gem 'rspec-rails', '2.5.0'
  gem 'annotate-models', '1.0.4'
  gem 'faker', '0.3.1'
  gem 'ruby_parser'
end

group :test do
  gem 'rspec', '2.5.0'
  gem 'webrat', '0.7.1'
  gem 'spork', '0.8.4'
  gem 'simplecov', '0.4.0'
end

