source 'http://rubygems.org'

gem 'rails', '3.0.4'

gem 'carrierwave'
gem 'declarative_authorization'
gem 'googlecalendar'
gem 'kramdown'
gem 'rack-openid'
gem 'ruby-openid'
gem 'sqlite3'

group :development do
  gem 'annotate-models'
  gem 'rspec-rails'
  gem 'ruby_parser'
end

group :test do
  gem 'rspec'
  gem 'simplecov'
  gem 'spork'
end

